#!/usr/bin/env bash

# O. sativa
# ======p1
nucmer --maxmatch --prefix=data/Oryza_sativa.IRGSP-1.0.dna.overlap_mummer --threads 40 /homeb/nipeng/data/genome/rice/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa /homeb/nipeng/data/genome/rice/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa
show-coords -rclT data/Oryza_sativa.IRGSP-1.0.dna.overlap_mummer.delta > data/Oryza_sativa.IRGSP-1.0.dna.overlap_mummer.coords

# ======p2
python s00_removeN_and_cut_genomeref.py --genome /homeb/nipeng/data/genome/rice/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.removeN_and_cut_genomeref.log
nucmer --maxmatch --prefix=data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer --threads 40 /homeb/nipeng/data/genome/rice/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.fa /homeb/nipeng/data/genome/rice/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.fa
show-coords -rclT data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.delta > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.coords
python s01_reformat_mummer_results_of_cuted_genome.py --crds_ref_file data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.coords

# ========= 20 0.99
python s1_extract_repeats_from_mummer.py --crds_ref_file data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords --len_cf 20 --identity_cf 99 --wfile data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_0.99.repeats &
python s2_reformat_mummer_repeats_file.py --repeat_file data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_0.99.repeats &
# ===
python s1_extract_repeats_from_mummer.py --crds_ref_file data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords --len_cf 20 --identity_cf 100 --wfile data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.repeats &
python s2_reformat_mummer_repeats_file.py --repeat_file data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.repeats &
python3 s3_group_mummer_repeats_file.py --repeat_file data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.repeats &
# == CG
python s4_get_rmet_of_seled_region.p1.py --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group --ref_fa /homeb/nipeng/data/genome/rice/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa --motifs CG --mod_loc 0 > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG.log &
# = 1-1
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao1-1/fast5/deepsignal2_comb.result/shuidao1-1.guppy.pass.part2.CG.bn13_sn16.arabnrice2-1.balance.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG --suffix _shuidao1-1 &
python s5_stat_diffmethyregions_info_from_repregions.p.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG.deepsignal_shuidao1-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG.deepsignal_shuidao1-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG.deepsignal_shuidao1-1.stat.log &
# = 2-1
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao2-1/fast5_pass/dp2_comb.results/shuidao2-1.guppy.pass.part2.CG.bn13_sn16.arabnrice2-1.balance.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG --suffix _shuidao2-1 &
python s5_stat_diffmethyregions_info_from_repregions.p.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG.deepsignal_shuidao2-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG.deepsignal_shuidao2-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.20_1.00.reformat.group.sites.CG.deepsignal_shuidao2-1.stat.log &



# ========= 100 0.99 main_contigs
python s1_extract_repeats_from_mummer.py --crds_ref_file data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords --len_cf 100 --identity_cf 99 --wfile data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.repeats --contig_names 1,2,3,4,5,6,7,8,9,10,11,12 &
python s2_reformat_mummer_repeats_file.py --repeat_file data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.repeats &
python3 s3_group_mummer_repeats_file.py --repeat_file data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.repeats &
# get pos info/rmet info ===
# CG ==
python s4_get_rmet_of_seled_region.p1.py --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group --ref_fa data/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa --motifs CG --mod_loc 0 > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.log &
# CG 2-1 rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao2-1/fast5_pass/dp2_comb.results/shuidao2-1.guppy.pass.part2.CG.bn13_sn16.arabnrice2-1.balance.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --suffix _2-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.deepsignal_2-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.deepsignal_2-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.deepsignal_2-1.stat.log &
# CG 2-1 rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao2-1/fast5_pass/bs.poses/shuidao2-1_1_bismark_bt2_pe.sorted.mark_dup.sorted.CX_report.CG.txt --rmet_type bs_rmet  --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --suffix _2-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.bs_rmet_2-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.bs_rmet_2-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.bs_rmet_2-1.stat.log &
# CG 1-1 rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao1-1/fast5/deepsignal2_comb.result/shuidao1-1.guppy.pass.part2.CG.bn13_sn16.arabnrice2-1.balance.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --suffix _1-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.deepsignal_1-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.deepsignal_1-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.deepsignal_1-1.stat.log &
# CG 1-1 rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao1-1/fast5/bs.poses/D1904161A-QJ_L2L4.cutadapt.R1_bismark_bt2_pe.sorted.mark_dup.sorted.CX_report.CG.txt --rmet_type bs_rmet --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --suffix _1-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.bs_rmet_1-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.bs_rmet_1-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.bs_rmet_1-1.stat.log &
# CHG ==
python s4_get_rmet_of_seled_region.p1.py --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group --ref_fa data/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa --motifs CHG --mod_loc 0 > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.log &
# CHG 2-1 rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao2-1/fast5_pass/dp2_comb.results/shuidao2-1.guppy.pass.part2.CHG.bn13_sn16.arabnrice2-1.denoise_signal_bilstm.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --suffix _2-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.deepsignal_2-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.deepsignal_2-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.deepsignal_2-1.stat.log &
# CHG 2-1 rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao2-1/fast5_pass/bs.poses/shuidao2-1_1_bismark_bt2_pe.sorted.mark_dup.sorted.CX_report.CHG.txt --rmet_type bs_rmet  --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --suffix _2-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.bs_rmet_2-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.bs_rmet_2-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.bs_rmet_2-1.stat.log &
# CHG 1-1 rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao1-1/fast5/deepsignal2_comb.result/shuidao1-1.guppy.pass.part2.CHG.bn13_sn16.arabnrice2-1.denoise_signal_bilstm.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --suffix _1-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.deepsignal_1-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.deepsignal_1-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.deepsignal_1-1.stat.log &
# CHG 1-1 rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao1-1/fast5/bs.poses/D1904161A-QJ_L2L4.cutadapt.R1_bismark_bt2_pe.sorted.mark_dup.sorted.CX_report.CHG.txt --rmet_type bs_rmet --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --suffix _1-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.bs_rmet_1-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.bs_rmet_1-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.bs_rmet_1-1.stat.log &
# CHH ==
python s4_get_rmet_of_seled_region.p1.py --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group --ref_fa data/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa --motifs CHH --mod_loc 0 > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.log &
# CHH 2-1 rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao2-1/fast5_pass/dp2_comb.results/shuidao2-1.guppy.pass.part2.CHH.bn13_sn16.arabnrice2-1.denoise_signal_bilstm.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --suffix _2-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.deepsignal_2-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.deepsignal_2-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.deepsignal_2-1.stat.log &
# CHH 2-1 rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao2-1/fast5_pass/bs.poses/shuidao2-1_1_bismark_bt2_pe.sorted.mark_dup.sorted.CX_report.CHH.txt --rmet_type bs_rmet  --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --suffix _2-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.bs_rmet_2-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.bs_rmet_2-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.bs_rmet_2-1.stat.log &
# CHH 1-1 rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao1-1/fast5/deepsignal2_comb.result/shuidao1-1.guppy.pass.part2.CHH.bn13_sn16.arabnrice2-1.denoise_signal_bilstm.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --suffix _1-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.deepsignal_1-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.deepsignal_1-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.deepsignal_1-1.stat.log &
# CHH 1-1 rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao1-1/fast5/bs.poses/D1904161A-QJ_L2L4.cutadapt.R1_bismark_bt2_pe.sorted.mark_dup.sorted.CX_report.CHH.txt --rmet_type bs_rmet --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --suffix _1-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.bs_rmet_1-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.bs_rmet_1-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.bs_rmet_1-1.stat.log &
# C ==
python s4_get_rmet_of_seled_region.p1.py --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group --ref_fa data/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa --motifs C --mod_loc 0 > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.log &
# C 2-1 rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao2-1/fast5_pass/dp2_comb.results/shuidao2-1.guppy.pass.part2.C.bn13_sn16.arabnrice2-1.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --suffix _2-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.deepsignal_2-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.deepsignal_2-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.deepsignal_2-1.stat.log &
# C 2-1 rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao2-1/fast5_pass/bs.poses/shuidao2-1_1_bismark_bt2_pe.sorted.mark_dup.sorted.CX_report.C.txt --rmet_type bs_rmet  --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --suffix _2-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.bs_rmet_2-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.bs_rmet_2-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.bs_rmet_2-1.stat.log &
# C 1-1 rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao1-1/fast5/deepsignal2_comb.result/shuidao1-1.guppy.pass.part2.C.bn13_sn16.arabnrice2-1.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --suffix _1-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.deepsignal_1-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.deepsignal_1-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.deepsignal_1-1.stat.log &
# C 1-1 rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/rice/shuidao1-1/fast5/bs.poses/D1904161A-QJ_L2L4.cutadapt.R1_bismark_bt2_pe.sorted.mark_dup.sorted.CX_report.C.txt --rmet_type bs_rmet --mum_region data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --suffix _1-1 &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.bs_rmet_1-1 --region_pos data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --outdir data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.bs_rmet_1-1.stat > data/Oryza_sativa.IRGSP-1.0.dna.toplevel.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.bs_rmet_1-1.stat.log &
















# A. thaliana
# ======p2
python s00_removeN_and_cut_genomeref.py --genome data/GCF_000001735.4_TAIR10.1_genomic.fna > data/GCF_000001735.4_TAIR10.1_genomic.removeN_and_cut_genomeref.log &
nucmer --maxmatch --prefix=data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer --threads 40 data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.fna data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.fna
show-coords -rclT data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.delta > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.coords
python s01_reformat_mummer_results_of_cuted_genome.py --crds_ref_file data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.coords

# ===
python s1_extract_repeats_from_mummer.py --crds_ref_file data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords --len_cf 100 --identity_cf 99 --wfile data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.repeats &
python s2_reformat_mummer_repeats_file.py --repeat_file data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.repeats &
python3 s3_group_mummer_repeats_file.py --repeat_file data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.reformat.repeats &

# === 100 0.99 main_contigs
python s1_extract_repeats_from_mummer.py --crds_ref_file data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords --len_cf 100 --identity_cf 99 --wfile data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.repeats --contig_prefix NC_003 &
python s2_reformat_mummer_repeats_file.py --repeat_file data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.repeats &
python3 s3_group_mummer_repeats_file.py --repeat_file data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.repeats &
# get pos info/rmet info ===
# CG ==
python s4_get_rmet_of_seled_region.p1.py --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group --ref_fa data/GCF_000001735.4_TAIR10.1_genomic.fna --motifs CG --mod_loc 0 > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.log &
# CG rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/arabidopsis/20190421-NPL0867-P1-E11-H11-barcode/deepsignal2_results/athaliana.guppy.pass.part2.CG.bn13_sn16.arabnrice2-1.balance.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.deepsignal --region_pos data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --outdir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.deepsignal.stat > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.deepsignal.stat.log &
# CG rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/arabidopsis/20190421-NPL0867-P1-E11-H11-barcode/bs.poses/ninanjie-2.CG.1n2n3.avg_rmet.covcf_5.bed --rmet_type bedmethyl --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.bedmethyl --region_pos data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG --outdir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.bedmethyl.stat > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CG.bedmethyl.stat.log &
# CHG ==
python s4_get_rmet_of_seled_region.p1.py --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group --ref_fa data/GCF_000001735.4_TAIR10.1_genomic.fna --motifs CHG --mod_loc 0 > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.log &
# CHG rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/arabidopsis/20190421-NPL0867-P1-E11-H11-barcode/deepsignal2_results/athaliana.guppy.pass.part2.CHG.bn13_sn16.arabnrice2-1.denoise_signal_bilstm.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.deepsignal --region_pos data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --outdir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.deepsignal.stat > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.deepsignal.stat.log &
# CHG rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/arabidopsis/20190421-NPL0867-P1-E11-H11-barcode/bs.poses/ninanjie-2.CHG.1n2n3.avg_rmet.covcf_5.bed --rmet_type bedmethyl --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.bedmethyl --region_pos data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG --outdir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.bedmethyl.stat > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHG.bedmethyl.stat.log &
# CHH ==
python s4_get_rmet_of_seled_region.p1.py --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group --ref_fa data/GCF_000001735.4_TAIR10.1_genomic.fna --motifs CHH --mod_loc 0 > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.log &
# CHH rmet nanopore
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/arabidopsis/20190421-NPL0867-P1-E11-H11-barcode/deepsignal2_results/athaliana.guppy.pass.part2.CHH.bn13_sn16.arabnrice2-1.denoise_signal_bilstm.both_bilstm.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.deepsignal --region_pos data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --outdir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.deepsignal.stat > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.deepsignal.stat.log &
# CHH rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/arabidopsis/20190421-NPL0867-P1-E11-H11-barcode/bs.poses/ninanjie-2.CHH.1n2n3.avg_rmet.covcf_5.bed --rmet_type bedmethyl --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.bedmethyl --region_pos data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH --outdir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.bedmethyl.stat > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.CHH.bedmethyl.stat.log &
# C ==
python s4_get_rmet_of_seled_region.p1.py --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group --ref_fa data/GCF_000001735.4_TAIR10.1_genomic.fna --motifs C --mod_loc 0 > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.log &
# C rmet nanopore
python3 s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/arabidopsis/20190421-NPL0867-P1-E11-H11-barcode/deepsignal2_results/athaliana.guppy.pass.part2.C.bn13_sn16.arabnrice2-1.50x_12345.p0.8.freq.tsv --rmet_type deepsignal --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.deepsignal --region_pos data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --outdir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.deepsignal.stat > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.deepsignal.stat.log &
# C rmet bs
python s4_get_rmet_of_seled_region.p2.py --rmet /homeb/nipeng/data/nanopore/arabidopsis/20190421-NPL0867-P1-E11-H11-barcode/bs.poses/ninanjie-2.C.1n2n3.avg_rmet.covcf_5.bed --rmet_type bedmethyl --mum_region data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C &
python3 s5_stat_diffmethyregions_info2.py --region_dir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.bedmethyl --region_pos data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C --outdir data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.bedmethyl.stat > data/GCF_000001735.4_TAIR10.1_genomic.rmN_cut.overlap_mummer.chr_offset2absloc.coords.100_0.99.main_contig.reformat.group.sites.C.bedmethyl.stat.log &















